---
- name: Create Postgres user
  kubernetes.core.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: v1
      kind: PostgresUser
      metadata:
        name: gitlab-database-role
        namespace: '{{ project_name }}'
      spec:
        name: '{{ gitlab_postgres_role }}'
        password: '{{ gitlab_postgres_password }}'
        superuser: True

- name: Create Postgres database
  kubernetes.core.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: v1
      kind: PostgresDatabase
      metadata:
        name: gitlab-database
        namespace: '{{ project_name }}'
      spec:
        name: '{{ gitlab_postgres_database }}'
        role: '{{ gitlab_postgres_role }}'

- name: Create LDAP group
  kubernetes.core.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: v1
      kind: LdapObject
      metadata:
        name: gitlab-ldap-group
        namespace: '{{ project_name }}'
        labels:
          app: gitlab
      spec:
        dn: 'cn={{ gitlab_ldap_group }},{{ ldap_groups_dn }}'
        values:
          - name: 'objectClass'
            value: 'groupOfUniqueNames'
          - name: 'objectClass'
            value: 'top'
  when: gitlab_ldap_enabled
