---
- name: Create Gitlab folder structure
  become: yes
  file:
    path: "{{ data_dir }}/gitlab/{{item}}"
    state: directory
    mode: 0755
    owner: "0"
    group: "0"
    recurse: no
  loop:
    - "config"
    - "logs"
    - "data"
    - "{{ (gitlab_git_data_path == '') | ternary('git', undefined) }}"
    - "{{ gitlab_minio_enabled | ternary('objects', undefined) }}"
  when: "item is not undefined"

- name: Create git-data folder
  become: yes
  file:
    path: "{{ gitlab_git_data_path }}"
    state: directory
    mode: 0755
    owner: "0"
    group: "0"
    recurse: no
  when: "gitlab_git_data_path != ''"

- name: Create object store folder
  become: yes
  file:
    path: "{{ gitlab_minio_path }}"
    state: directory
    mode: 0755
    owner: "0"
    group: "0"
    recurse: no
  when: "gitlab_minio_path != ''"

- name: Create Postgres user
  kubernetes.core.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: v1
      kind: PostgresUser
      metadata:
        name: gitlab-database-role
        namespace: '{{ project_name }}'
      spec:
        name: '{{ gitlab_postgres_role }}'
        password: '{{ gitlab_postgres_password }}'
        superuser: True

- name: Create Postgres database
  kubernetes.core.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: v1
      kind: PostgresDatabase
      metadata:
        name: gitlab-database
        namespace: '{{ project_name }}'
      spec:
        name: '{{ gitlab_postgres_database }}'
        role: '{{ gitlab_postgres_role }}'
