---
- name: Pull redis image
  docker_pull_push:
    image: '{{ gitlab_redis_image }}'
    address: '{{ registry_address }}'
  register: registry_gitlab_redis_image

- name: Create redis service
  kubernetes.core.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: gitlab-redis
        namespace: '{{ project_name }}'
        labels:
          app: gitlab-redis
      spec:
        type: ClusterIP
        ports:
          - port: 6379
            name: web
            protocol: TCP
        selector:
          app: gitlab-redis

- name: Create deployment
  kubernetes.core.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: gitlab-redis
        namespace: '{{ project_name }}'
        labels:
          app: gitlab-redis
      spec:
        replicas: 1
        strategy:
          type: Recreate
        revisionHistoryLimit: 0
        selector:
          matchLabels:
            app: gitlab-redis
        template:
          metadata:
            name: gitlab-redis
            namespace: '{{ project_name }}'
            labels:
              app: gitlab-redis
          spec:
            containers:
              - name: gitlab-redis
                image: '{{ registry_gitlab_redis_image.name }}'
                imagePullPolicy: "IfNotPresent"
                command: 'redis-server'
                args:
                  - '--requirepass'
                  - '{{ gitlab_redis_password }}'
                ports:
                  - name: web
                    containerPort: 6379

- name: Wait for service ready
  kubernetes.core.k8s_info:
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    kind: Deployment
    namespace: '{{ project_name }}'
    name: 'gitlab-redis'
    label_selectors: 
      - app = gitlab-redis
  register: output_info
  until: output_info | json_query('resources[*].status.readyReplicas') | select ('match','1') | list | length == 1
  delay: 10
  retries: 6
