# permissions for end users to view postgresdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresdatabase-viewer-role
rules:
- apiGroups:
  - postgres.matusnovak.com
  resources:
  - postgresdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.matusnovak.com
  resources:
  - postgresdatabases/status
  verbs:
  - get
