
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - postgres.matusnovak.com
  resources:
  - postgresdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.matusnovak.com
  resources:
  - postgresdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.matusnovak.com
  resources:
  - postgresdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres.matusnovak.com
  resources:
  - postgresusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.matusnovak.com
  resources:
  - postgresusers/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.matusnovak.com
  resources:
  - postgresusers/status
  verbs:
  - get
  - patch
  - update
