version: "3.7"
networks:
  default:
    external:
      name: "homelab_base_default"
services:
  organizr:
    image: "linuxserver/organizr:${ORGANIZR_VERSION}"
    restart: "unless-stopped"
    environment:
      PUID: "1000"
      GUID: "1000"
      TZ: "Europe/London"
    volumes:
      - "./data/organizr/data:/config"
      - "./data/organizr/images:/var/www/html/images"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.organizr.loadbalancer.server.port=80"
      - "traefik.http.routers.organizr.rule=Host(`home.${DOMAIN_NAME}`)"
      - "traefik.http.routers.organizr.entrypoints=web-secure"
      - "traefik.http.routers.organizr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.organizr.middlewares=authelia@docker"
