---
- hosts: homelab
  roles:
    # List of apps to deploy
    # Uncomment them in order to enable them
    # (i.e. remove '#' before '- appname')
    
    # [Haste]
    # Haste is an open-source pastebin software written in node.js
    # No config file
    # - haste

    # [Portainer]
    # Portainer is a universal container management tool for Docker.
    # Config file: group_vars/homelab/portainer.yml
    # - portainer
    
    # [phpLDAPadmin]
    # phpLDAPadmin is a web app for administering Lightweight Directory 
    # Access Protocol servers.
    # Config file: None
    # - phpldapadmin
    
    # [Adminer]
    # Database management in a single PHP file.
    # Config file: None
    # - adminer
    
    # [FileBrowser]
    # FileFrowser provides a file managing interface
    # Config file: group_vars/homelab/filebrowser.yml
    # - filebrowser
    
    # [DevDocs]
    # DevDocs combines multiple API documentations in a fast, organized, and searchable interface. 
    # Config file: None
    # - devdocs
