{{- if .Values.persistentVolume.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "grafana.persistentVolumeName" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  {{- with .Values.persistentVolume.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.global.dataDir }}/grafana/data
{{- end -}}
