---
- name: Check if traefik role is included
  fail:
    msg: "Adminer needs the traefik role"
  when: "'traefik' not in role_names"

- name: Deploy service
  docker_swarm_service:
    project_name: "{{ project_name }}"
    definition:
      devdocs:
        image: "{{ devdocs_image }}"
        restart_policy:
          condition: "any"
        deploy:
          replicas: 1
          placement:
            constraints: "{{ devdocs_constraints }}"
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.devdocs.rule=Host(`devdocs.{{ domain_name }}`)"
            - "traefik.http.services.devdocs.loadbalancer.server.port=9292"
            - "traefik.http.routers.devdocs.entrypoints={{ traefik_entrypoints }}"
            - "traefik.http.routers.devdocs.tls={{ traefik_tls }}"
            - "traefik.http.routers.devdocs.tls.certresolver={{ traefik_certresolver }}"
        networks:
          - "{{ docker_network_name }}"
  register: result

- name: Set facts
  set_fact:
    devdocs_service: "{{ result.services.devdocs }}"

- name: Healthcheck (may take a while)
  http_wait:
    url: "{{ traefik_address }}/"
    status_code: "200"
    retries: 6
    delay: 30
    headers:
      - "Host: devdocs.{{ domain_name }}"
