---
- name: Deploy DevDocs
  docker_deploy:
    host: "{{ docker.host }}"
    project: "{{ project_name }}"
    container:
      image: "{{ images.devdocs }}"
      name: "devdocs"
      networks:
        - name: "{{ docker_network.name }}"
          alias: "devdocs"
      labels:
        - key: "traefik.enable"
          value: "true"
        - key: "traefik.http.services.devdocs.loadbalancer.server.port"
          value: "9292"
        - key: "traefik.http.routers.devdocs.rule"
          value: "Host(`devdocs.{{ domain_name }}`)"
        - key: "traefik.http.routers.devdocs.entrypoints"
          value: "{{ traefik_entrypoints }}"
        - key: "traefik.http.routers.devdocs.tls.certresolver"
          value: "{{ traefik_certresolver }}"
        - key: "traefik.http.routers.devdocs.tls"
          value: "{{ 'true' if traefik.https.enabled else 'false' }}"
  register: container_devdocs

- name: Healthcheck for DevDocs 
  http_wait:
    url: "{{traefik_entrypoint}}"
    status_code: "200"
    retries: 3
    delay: 5
    headers:
      - "Host: devdocs.{{ domain_name }}"
