---
- name: Check if go is installed
  shell: command -v go >/dev/null 2>&1
  register: go_exist
  ignore_errors: yes
  changed_when: no

- name: Install golang
  when: go_exist.rc != 0
  block:

    - name: Install snap
      apt:
        name: snapd
        state: present
      become: yes

    - name: Install go
      snap:
        name: go
        classic: yes
      become: yes
