apiVersion: v1
kind: Service
metadata:
  name: {{ include "phpldapadmin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "phpldapadmin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      protocol: TCP
      name: web
  selector:
    {{- include "phpldapadmin.selectorLabels" . | nindent 4 }}
