apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ldapobjects.homelab.local

spec:
  group: homelab.local
  names:
    kind: LdapObject
    plural: ldapobjects
    singular: ldapobject
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
