---
- name: Deploy WhatsApp bridge
  import_tasks: whatsapp.yml
  when: "matrix.whatsapp.enabled"

- name: Deploy Synapse
  import_tasks: synapse.yml

- name: Deploy Element
  import_tasks: element.yml
  when: "matrix.element.enabled"
