{{- if .Values.promtail.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" .Release.Namespace (include "loki.promtail.clusterRoleName" .) }}
  labels:
    {{- include "loki.promtail.labels" . | nindent 4 }}
  {{- with .Values.promtail.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'nodes'
      - 'nodes/proxy'
      - 'services'
      - 'endpoints'
      - 'pods'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
{{- end }}
