---
- name: Check if microk8s is installed
  shell: command -v microk8s >/dev/null 2>&1
  register: microk8s_exist
  ignore_errors: yes
  changed_when: no

- name: Install microk8s
  when: microk8s_exist.rc != 0
  block:

    - name: Install snap
      apt:
        name: snapd
        state: present
      become: yes

    - name: Install microk8s from snap
      snap:
        name: microk8s
        classic: yes
      become: yes

    - name: Get microk8s status
      shell: 'microk8s status --wait-ready'
      changed_when: no
      become: yes
        
    - name: Get user id
      set_fact:
        user_id: '{{ ansible_user_id }}'

    - name: Get user home folder
      set_fact:
        user_home: "{{ lookup('env', 'HOME') }}"

    - name: Create kube folder
      ansible.builtin.file:
        path: '{{ user_home }}/.kube'
        state: directory
        mode: '0750'

    - name: Check for config
      stat:
        path: '{{ user_home }}/.kube/config'
      register: config_result

    - name: Create config
      shell: 'microk8s kubectl config view --raw > {{ user_home }}/.kube/config'
      become: yes
      when: not config_result.stat.exists

    - name: Set the owner of the kube folder
      shell: 'chown -f -R {{ user_id }} {{ user_home }}/.kube'
      become: yes

    - name: Set the permissions for kube config
      shell: 'chmod go-rx {{ user_home }}/.kube/config'
      become: yes

    - name: Add the user to microk8s group
      shell: 'usermod -a -G microk8s {{ user_id }}'
      become: yes

    - name: newgrp microk8s
      shell: 'newgrp microk8s'

- name: Get microk8s status
  shell: 'microk8s status --wait-ready'
  changed_when: no

- name: Enable addons
  shell: 'microk8s enable registry dns storage metallb'
  register: output
  changed_when: "'created' in output.stdout"
