apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authelia.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "authelia.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "authelia.server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "authelia.server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ printf "%s-ldap" .Chart.Name }}
          image: "{{ .Values.global.openldapCheck.repository }}:{{ .Values.global.openldapCheck.tag }}"
          imagePullPolicy: {{ .Values.global.openldapCheck.pullPolicy }}
          command:
            - 'sh'
            - '-c'
            - 'until ldapsearch -x -H "ldap://$LDAP_HOST:389" -D "$LDAP_USER" -w "$LDAP_PASSWORD" -b "$LDAP_BASE"; do echo "waiting for openldap"; sleep 2; done;'
          env:
            - name: LDAP_HOST
              value: {{ printf "%s.%s.svc.cluster.local" (include "openldap.fullname" .) .Release.Namespace }}
            - name: LDAP_USER
              value: '{{ printf "cn=readonly,%s" .Values.global.domainComponent }}'
            - name: LDAP_PASSWORD
              value: '{{ .Values.server.openldap.readonlyPassword }}'
            - name: LDAP_BASE
              value: '{{ printf "ou=%s,%s" .Values.server.openldap.users .Values.global.domainComponent }}'
        - name: {{ printf "%s-psql" .Chart.Name }}
          image: "{{ .Values.global.postgresCheck.repository }}:{{ .Values.global.postgresCheck.tag }}"
          imagePullPolicy: {{ .Values.global.postgresCheck.pullPolicy }}
          command:
            - 'sh'
            - '-c'
            - 'until psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_ROLE -d $POSTGRES_DB -c "select 1"; do echo "waiting for database"; sleep 2; done;'
          env:
            - name: POSTGRES_HOST
              value: {{ printf "%s.%s.svc.cluster.local" (include "postgres.fullname" .) .Release.Namespace }}
            - name: POSTGRES_DB
              value: {{ .Values.server.postgres.database }}
            - name: POSTGRES_ROLE
              value: {{ .Values.server.postgres.role }}
            - name: POSTGRES_PORT
              value: '5432'
            - name: PGPASSWORD
              value: '{{ .Values.server.postgres.password }}'
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          {{- with .Values.server.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: web
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: web
          readinessProbe:
            httpGet:
              path: /
              port: web
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /config/configuration.yml
              subPath: configuration.yml
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "authelia.server.fullname" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authelia.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "authelia.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "authelia.redis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.redis.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "authelia.redis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          {{- with .Values.redis.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - 'redis-server'
          args:
            - '--requirepass'
            - '{{ .Values.redis.password }}'
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
