{{ $fullname := (include "openldap.fullname" .) }}
{{ $labels := (include "authelia.server.labels" .) }}
{{- range .Values.server.rules }}
---
apiVersion: homelab.local/v1alpha1
kind: LdapObject
metadata:
  name: {{ printf "%s-group-%s" $fullname .ldapGroup }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  dn: {{ printf "cn=%s,ou=%s,%s" .ldapGroup $.Values.server.openldap.groups $.Values.global.domainComponent }}
  attributes:
    - name: 'objectClass'
      value: 'groupOfUniqueNames'
    - name: 'objectClass'
      value: 'top'
    - name: 'uniqueMember'
      value: '{{ printf "cn=admin,%s" $.Values.global.domainComponent }}'
{{- end }}
