{{- if .Values.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "authelia.server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.server.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.redis.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "authelia.redis.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.redis.labels" . | nindent 4 }}
  {{- with .Values.redis.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
