apiVersion: v1
kind: Service
metadata:
  name: {{ include "authelia.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: 9091
      protocol: TCP
      name: web
  selector:
    {{- include "authelia.server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authelia.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "authelia.redis.selectorLabels" . | nindent 4 }}
