apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
data:
  traefik.yml: |
    entryPoints:
      {{- if .Values.http.enabled }}
      web:
        address: ":80"
      {{- end }}
      {{- if .Values.https.enabled }}
      websecure:
        address: ":443"
      {{- end }}
    {{- if .Values.accessLog.enabled }}
    accessLog: {}
    {{- end }}
    log:
      level: {{ .Values.log.level }}
    api:
      dashboard: {{ .Values.dashboard.enabled }}
      insecure: true
    providers:
      kubernetesCRD:
        namespaces:
          - {{ .Release.Namespace }}
          {{- range .Values.allowedNamespaces }}
          - {{ . }}
          {{- end }}
        allowCrossNamespace: false
      kubernetesingress: {}
    {{- if .Values.acme.enabled }}
    certificatesResolvers:
      letsencrypt:
        acme:
          email: "{{ .Values.acme.email }}"
          storage: "/certs/acme.json"
    {{- if eq .Values.acme.challenge "web" }}
          httpChallenge:
            entryPoint: "web"
    {{- end }}
    {{- if eq .Values.acme.challenge "websecure" }}
          httpChallenge:
            entryPoint: "websecure"
    {{- end }}
    {{- if eq .Values.acme.challenge "dns" }}
          dnsChallenge:
            provider: "{{ .Values.acme.dnsChallengeProvider }}"
            resolvers:
              {{- range .Values.acme.dnsChallengeResolvers }}
              - {{ . }}
              {{- end }}
    {{- end }}
    {{- end }}
    {{- if  .Values.metrics.enabled }}
    metrics:
      prometheus:
        entryPoint: "traefik"
        buckets:
          - 0.1
          - 0.3
          - 1.2
          - 5.0
    {{- end }}
