{{- if .Values.redirectHttpToHttps.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-https-redirect" (include "traefik.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end -}}
{{- if .Values.forwardAuth.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-forward-auth" (include "traefik.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: {{ printf "http://%s.%s.svc.cluster.local:9091/api/verify?rd=%s://auth.%s/" (include "authelia.fullname" .) .Release.Namespace (ternary "https" "http" .Values.https.enabled) .Values.global.domainName }}
    trustForwardHeader: true
    authResponseHeaders:
      - 'Remote-User'
      - 'Remote-Groups'
{{- end -}}
