apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.http.enabled }}
    - port: 80
      nodePort: {{ .Values.http.nodePort }}
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.https.enabled }}
    - port: 443
      nodePort: {{ .Values.https.nodePort }}
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "traefik.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "traefik.fullname" .) "internal" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  type: {{ .Values.serviceInternal.type }}
  ports:
    - port: 8080
      protocol: TCP
      name: api
  selector:
    {{- include "traefik.selectorLabels" . | nindent 4 }}
