{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" .Release.Namespace (include "prometheus.clusterRoleName" .) }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'nodes'
      - 'nodes/proxy'
      - 'nodes/metrics'
      - 'services'
      - 'endpoints'
      - 'pods'
      - 'ingresses'
      - 'configmaps'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'extensions'
      - 'networking.k8s.io'
    resources:
      - 'ingresses/status'
      - 'ingresses'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - nonResourceURLs:
      - '/metrics'
    verbs:
      - 'get'
{{- end }}
