apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "nodeexporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nodeexporter.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "nodeexporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nodeexporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nodeexporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - '--path.sysfs=/host/sys'
            - '--path.rootfs=/host/root'
            - '--no-collector.wifi'
            - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)'
            - '--collector.cpu'
            - '--collector.cpufreq'
            - '--collector.diskstats'
            - '--collector.filesystem'
            - '--collector.netclass'
            - '--collector.netdev'
            - '--collector.netstat'
            - '--collector.hwmon'
            - '--collector.meminfo'
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: hostfs-volume
              mountPath: /host/root
              readOnly: true
              mountPropagation: HostToContainer
            - name: sys-volume
              mountPath: /host/sys
              readOnly: true
              mountPropagation: HostToContainer
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: hostfs-volume
          hostPath:
            path: /
        - name: sys-volume
          hostPath:
            path: /sys
