{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" .Release.Namespace (include "postgres-controller.clusterRoleName" .) }}
  labels:
    {{- include "postgres-controller.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups:
      - 'kopf.dev'
    resources:
      - 'clusterkopfpeerings'
    verbs:
      - 'list'
      - 'watch'
      - 'patch'
      - 'get'
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups:
      - 'apiextensions.k8s.io'
    resources:
      - 'customresourcedefinitions'
    verbs:
      - 'list'
      - 'watch'
  - apiGroups:
      - ''
    resources:
      - 'namespaces'
    verbs:
      - 'list'
      - 'watch'

  # Framework: admission webhook configuration management.
  - apiGroups:
      - 'admissionregistration.k8s.io/v1'
      - 'admissionregistration.k8s.io/v1beta1'
    resources:
      - 'validatingwebhookconfigurations'
      - 'mutatingwebhookconfigurations'
    verbs:
      - 'create'
      - 'patch'
  
  # Application: read-only access for watching cluster-wide.
  - apiGroups:
      - 'homelab.local'
    resources:
      - 'postgresdatabases'
    verbs:
      - 'list'
      - 'watch'
{{- end }}
