apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 389
      protocol: TCP
      name: openldap
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
