{{- if .Values.synapse.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matrix.synapse.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix.synapse.labels" . | nindent 4 }}
  {{- with .Values.synapse.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
