---
- name: 'Install python dependencies'
  pip:
    name: ['requests', 'docker']
    state: 'latest'

- name: 'Copy Dockerfile for script runner image'
  copy:
    src: 'roles/base/files/scriptrunner'
    dest: '/tmp'

- name: 'Create image for running scripts'
  docker_build:
    docker:
      host: '{{ docker.host }}'
    path: '/tmp/scriptrunner'
    name: '{{ project_name }}_scriptrunner'
  register: 'scriptrunner'

- name: 'Create shared docker network'
  docker_network:
    host: '{{ docker.host }}'
    project: '{{ project_name }}'
    network:
      name: 'default'
      attachable: true
  register: 'docker_network'

- name: Collect only facts returned by facter
  ansible.builtin.debug:
    msg: 'Docker host: {{ docker.host }} network: {{ docker_network.subnet }}'

