---
- name: Check that the data dir exists
  stat:
    path: "{{ data_dir }}"
  register: result

- name: Fail if data dir does not exist
  fail:
    msg: The folder {{ data_dir }} must be created by you!
  when: not result.stat.exists

- name: Install python dependencies
  pip:
    name: ["requests", "docker"]
    state: latest

- name: Check for Docker Swarm
  docker_swarm_info:
  register: docker_swarm_info

- name: Create shared network
  docker_network:
    name: "{{ docker_network_name }}"
    driver: overlay
    attachable: "{{ docker_network_attachable }}"
    ipam_config: "{{ docker_network_ipam }}"
  register: result

- name: Set facts
  set_fact:
    docker_network: "{{ result.network }}"
    docker_network_lb_name: "lb-{{ docker_network_name }}"

- name: Inspect Docker gwbridge
  docker_network:
    name: "docker_gwbridge"
  register: result

- name: Set facts
  set_fact:
    docker_gateway_address: "{{ result.network.IPAM.Config[0].Gateway }}"
