---
- name: Check that the data dir exists
  stat:
    path: "{{ data_dir }}"
  register: result

- name: Fail if data dir does not exist
  fail:
    msg: The folder {{ data_dir }} must be created by you!
  when: not result.stat.exists

- name: Install python dependencies
  pip:
    name: ["requests", "docker"]
    state: latest

- name: Check for Docker Swarm
  docker_swarm_info:
  register: docker_swarm_info

- name: Create shared network
  docker_network:
    name: "{{ docker_network_name }}"
    driver: overlay
    attachable: "{{ docker_network_attachable }}"
  register: result

- name: Set facts
  set_fact:
    docker_network: "{{ result.ansible_facts.docker_network }}"

- name: Find shared network load balancer
  set_fact:
    docker_network_load_balancer: "{{ docker_network.Containers['lb-' + docker_network_name]['IPv4Address'].split('/')[0] }}"