---
- name: Install extra python3 dependencies
  pip:
    name: ['requests', 'openshift', 'PyYAML', 'jmespath']
    state: latest
    executable: pip3

- name: Install extra python2 dependencies
  pip:
    name: ['jmespath']
    state: latest
    executable: pip

- name: Install extra apt packages
  apt:
    name: 'python3-jmespath'
    state: present
  become: yes

- name: Check kubernetes cluster info
  community.kubernetes.k8s_cluster_info:
    invalidate_cache: False
  register: k8s_status

- name: Create namespace
  community.kubernetes.k8s:
    name: '{{ project_name }}'
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    kind: Namespace
    state: present
