---
# https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-crd/#definitions
- name: Create CRD - IngressRoute
  community.kubernetes.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: ingressroutes.traefik.containo.us
      spec:
        group: traefik.containo.us
        version: v1alpha1
        names:
          kind: IngressRoute
          plural: ingressroutes
          singular: ingressroute
        scope: Namespaced

- name: Create CRD - Middleware
  community.kubernetes.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: middlewares.traefik.containo.us
      spec:
        group: traefik.containo.us
        version: v1alpha1
        names:
          kind: Middleware
          plural: middlewares
          singular: middleware
        scope: Namespaced

- name: Create CRD - IngressRouteTCP
  community.kubernetes.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: ingressroutetcps.traefik.containo.us
      spec:
        group: traefik.containo.us
        version: v1alpha1
        names:
          kind: IngressRouteTCP
          plural: ingressroutetcps
          singular: ingressroutetcp
        scope: Namespaced

- name: Create CRD - IngressRouteUDP
  community.kubernetes.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: ingressrouteudps.traefik.containo.us
      spec:
        group: traefik.containo.us
        version: v1alpha1
        names:
          kind: IngressRouteUDP
          plural: ingressrouteudps
          singular: ingressrouteudp
        scope: Namespaced

- name: Create CRD - TLSOption
  community.kubernetes.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: tlsoptions.traefik.containo.us
      spec:
        group: traefik.containo.us
        version: v1alpha1
        names:
          kind: TLSOption
          plural: tlsoptions
          singular: tlsoption
        scope: Namespaced
  
- name: Create CRD - TLSStore
  community.kubernetes.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: tlsstores.traefik.containo.us
      spec:
        group: traefik.containo.us
        version: v1alpha1
        names:
          kind: TLSStore
          plural: tlsstores
          singular: tlsstore
        scope: Namespaced

- name: Create CRD - TraefikService
  community.kubernetes.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: traefikservices.traefik.containo.us
      spec:
        group: traefik.containo.us
        version: v1alpha1
        names:
          kind: TraefikService
          plural: traefikservices
          singular: traefikservice
        scope: Namespaced

- name: Create CRD - ServersTransport
  community.kubernetes.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: serverstransports.traefik.containo.us
      spec:
        group: traefik.containo.us
        version: v1alpha1
        names:
          kind: ServersTransport
          plural: serverstransports
          singular: serverstransport
        scope: Namespaced
