---
- include_tasks: 'traefik.yml'
- include_tasks: 'crd.yml'
- include_tasks: 'rbac.yml'

- name: Create dashboard route
  kubernetes.core.k8s:
    state: present
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: traefik-dashboard-ingress
        namespace: '{{ project_name }}'
      spec:
        entryPoints:
          - web
          - websecure
        routes:
          - match: Host(`traefik.{{ domain_name }}`)
            kind: Rule
            services:
              - name: api@internal
                kind: TraefikService
        tls: {}
  when: traefik_dashboard_enabled

- name: Healthcheck
  http_wait:
    url: '{{ traefik_address }}/'
    status_code: '200, 304'
    retries: 3
    delay: 10
    headers:
      - 'Host: traefik.{{ domain_name }}'
  when: traefik_dashboard_enabled
