---
- include_role:
    name: base

- name: Create traefik folder structure
  become: yes
  file:
    path: "{{ base.destination}}/data/traefik/{{item}}"
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes
  loop:
    - "config"

- name: Create traefik config files
  become: yes
  template:
    src: "roles/traefik/files/{{item}}.j2"
    dest: "{{ base.destination}}/data/traefik/{{item}}"
  loop:
    - "traefik.yml"
    - "config/middlewares.yml"
    - "config/routers.yml"
    - "config/services.yml"

- name: Create traefik acme.json file
  become: yes
  copy:
    content: "{}"
    dest: "{{ base.destination}}/data/traefik/acme.json"
    force: no
    mode: 0600
    owner: root
    group: root

- name: Set traefik entrypoints
  set_fact:
    traefik_entrypoints: >-
      {%- if traefik.http.enabled and traefik.https.enabled -%}
      web,web-secure
      {%- elif traefik.https.enabled -%}
      web-secure
      {%- else -%}
      web
      {%- endif -%}

- name: Set traefik certs resolver
  set_fact:
    traefik_certresolver: >-
      {%- if traefik.https.enabled and traefik.acme.enabled -%}
      letsencrypt
      {%- else -%}
      {%- endif -%}

- name: Docker check
  ansible.builtin.debug:
    msg: 'Docker host: {{ docker.host }} network: {{ docker_network.subnet }}'

- name: Deploy traefik
  docker_deploy:
    host: '{{ docker.host }}'
    project: '{{ base.name }}'
    container:
      image: "{{ base.registry }}/{{ images.traefik }}"
      name: "traefik"
      network:
        name: "{{ docker_network.name }}"
        alias: "traefik"
      ports:
        - host: "{{ traefik.https.port }}"
          guest: "443"
          protocol: "tcp"
        - host: "{{ traefik.http.port }}"
          guest: "80"
          protocol: "tcp"
      volumes:
        - host: "/var/run/docker.sock" # TODO
          guest: "/var/run/docker.sock"
          read_only: false
        - host: "{{ base.destination }}/data/traefik/traefik.yml"
          guest: "/etc/traefik/traefik.yml"
          read_only: true
        - host: "{{ base.destination }}/data/traefik/config"
          guest: "/config"
          read_only: true
        - host: "{{ base.destination }}/data/traefik/acme.json"
          guest: "/acme.json"
          read_only: false
      labels:
        - key: "traefik.enable"
          value: "{{ 'true' if traefik.dashboard.enabled else 'false' }}"
        - key: "traefik.http.services.traefik.loadbalancer.server.port"
          value: "8080"
        - key: "traefik.http.routers.traefik.rule"
          value: "Host(`traefik.{{ base.hostname }}`)"
        - key: "traefik.http.routers.traefik.entrypoints"
          value: "{{ traefik_entrypoints }}"
        - key: "traefik.http.routers.traefik.tls.certresolver"
          value: "{{ traefik_certresolver }}"
        - key: "traefik.http.routers.traefik.middlewares"
          value: "{{ 'authelia@docker' if traefik.dashboard.authelia else '' }}"
