{{ $configMapHash := include (print $.Template.BasePath "/nginx/configmap.yml") . | sha256sum }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrix.nginx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix.nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "matrix.nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ $configMapHash }}
      {{- with .Values.nginx.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "matrix.nginx.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nginx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "matrix.nginx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.nginx.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          {{- with .Values.nginx.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /.well-known/matrix/server
              port: web
              scheme: HTTP
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /.well-known/matrix/server
              port: web
              scheme: HTTP
            initialDelaySeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/matrix.conf
              subPath: matrix.conf
              readOnly: true
            - name: config-volume
              mountPath: /var/www/.well-known/matrix/server
              subPath: server
              readOnly: true
            - name: config-volume
              mountPath: /var/www/.well-known/matrix/client
              subPath: client
              readOnly: true
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "matrix.nginx.fullname" . }}
