apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.nginx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix.nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: 80
      protocol: TCP
      name: web
  selector:
    {{- include "matrix.nginx.selectorLabels" . | nindent 4 }}
