---
- name: Build Postgres CRD controller
  make:
    chdir: 'resources/postgres'
    target: 'docker-build'
    params:
      IMG: 'localhost:32000/matusnovak/k8s-postgres-controller:latest'

- name: Push Postgres CRD controller
  make:
    chdir: 'resources/postgres'
    target: 'docker-push'
    params:
      IMG: 'localhost:32000/matusnovak/k8s-postgres-controller:latest'

- name: Install Postgres CRD controller
  make:
    chdir: 'resources/postgres'
    target: 'install'
    params:
      IMG: 'localhost:32000/matusnovak/k8s-postgres-controller:latest'

- name: Deploy Postgres CRD controller
  make:
    chdir: 'resources/postgres'
    target: 'deploy'
    params:
      IMG: 'localhost:32000/matusnovak/k8s-postgres-controller:latest'

- name: Wait for CRD ready
  community.kubernetes.k8s_info:
    verify_ssl: '{{ k8s_ssl_verify }}'
    api_version: '{{ k8s_api_version }}'
    api_key: '{{ k8s_api_key }}'
    kind: Deployment
    namespace: 'postgres-system'
    name: 'postgres-controller-manager'
  register: output_info
  until: output_info | json_query('resources[*].status.readyReplicas') | select ('match','1') | list | length == 1
  delay: 5
  retries: 0
  