---
- name: Check if base role is included
  fail:
    msg: "Postgre SQL needs the base role"
  when: "'base' not in role_names"

- name: Create folder structure
  become: yes
  file:
    path: "{{ data_dir }}/postgres/{{ item }}"
    state: directory
    mode: "0700"
    owner: "999"
    group: "0"
    recurse: false
  loop:
    - data

- name: Deploy service
  docker_swarm_service:
    project_name: "{{ project_name }}"
    definition:
      postgres:
        image: "{{ postgres_image }}"
        restart_policy:
          condition: "any"
        deploy:
          replicas: 1
          placement:
            constraints: "{{ postgres_constraints }}"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5
        networks:
          - "{{ docker_network_name }}"
        volumes:
          - "{{ data_dir }}/postgres/data:/var/lib/postgresql/data"
        environment:
          POSTGRES_PASSWORD: "{{ postgres_password }}"
  register: result

- name: Set facts
  set_fact:
    postgres_service: "{{ result.services.postgres }}"

- name: Healthcheck
  postgres_query:
    container: "{{ postgres_service.tasks[0].id }}"
    password: "{{ postgres_password }}"
    query: "SELECT version();"
