---
- name: Create PostgreSQL folder structure
  become: yes
  file:
    path: "{{ data_dir }}/data/postgres/{{item}}"
    state: directory
    mode: 0700
    owner: "999"
    group: "0"
    recurse: false
  loop:
    - "data"

- name: Deploy PostgreSQL
  docker_deploy:
    host: "{{ docker.host }}"
    project: "{{ project_name }}"
    container:
      image: "{{ images.postgres }}"
      name: "postgres"
      networks:
        - name: "{{ docker_network.name }}"
          alias: "postgres"
      volumes:
        - host: "{{ data_dir }}/data/postgres/data"
          guest: "/var/lib/postgresql/data"
          read_only: false
      environment:
        - key: "POSTGRES_PASSWORD"
          value: "{{ passwords.postgres_admin }}"
  register: postgres_container

- name: Healthcheck for PostgreSQL 
  psql_exec:
    host: "{{ docker.host }}"
    container: "{{ postgres_container.id }}"
    dbname: "postgres"
    user: "postgres"
    password: "{{ passwords.postgres_admin }}"
    query: "SELECT version();"
  when: traefik.https.enabled
