---
- name: Create PostgreSQL folder structure
  become: yes
  file:
    path: "{{ data_dir }}/data/postgres/{{item}}"
    state: directory
    mode: 0700
    owner: "999"
    group: "0"
    recurse: false
  loop:
    - "data"

- name: Deploy PostgreSQL
  docker_deploy:
    host: "{{ docker.host }}"
    project: "{{ project_name }}"
    container:
      image: "{{ images.postgres }}"
      name: "postgres"
      networks:
        - name: "{{ docker_network.name }}"
          alias: "postgres"
      volumes:
        - host: "{{ data_dir }}/data/postgres/data"
          guest: "/var/lib/postgresql/data"
          read_only: false
      environment:
        - key: "POSTGRES_PASSWORD"
          value: "{{ passwords.postgres_admin }}"
  register: container_postgres

- name: Copy script for PostgreSQL
  copy:
    src: "roles/postgres/files/postgres.py"
    dest: "/tmp/postgres.py"

- name: Healthcheck for PostgreSQL 
  docker_script:
    docker:
      host: "{{ docker.host }}"
    network: "{{ docker_network.name }}"
    image: "{{ scriptrunner.id }}"
    script: "/tmp/postgres.py"
    args:
      - "query"
      - |
        {
          "host": "{{ container_postgres.alias }}",
          "user": "postgres",
          "password": "{{ passwords.postgres_admin }}",
          "port": 5432,
          "database": "postgres",
          "query": "SELECT version();"
        }
