apiVersion: v1
kind: Service
metadata:
  name: {{ include "adminer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
      name: web
  selector:
    {{- include "adminer.selectorLabels" . | nindent 4 }}
