{{- if .Values.redis.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matrix.redis.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix.redis.labels" . | nindent 4 }}
  {{- with .Values.redis.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
