name: integration
on: [push, pull_request]
jobs:
  apps:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Adminer'
            role: 'adminer'
          - name: 'Postgre SQL'
            role: 'postgres'
          - name: 'Traefik'
            role: 'traefik'

    name: 'App: ${{ matrix.name }}'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Ansible
        run: |
          echo "---" >> site.yml
          echo "- hosts: homelab" >> site.yml
          echo "  roles:" >> site.yml
          echo "    - ${{ matrix.role }}" >> site.yml
          ansible-playbook -vvv -i hosts site.yml

      - name: Dump logs
        if: ${{ always() }}
        run: |
          ./.github/dump.sh

      - name: Store logs as artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }} Logs
          path: /tmp/microk8s/
