name: integration
on: [push, pull_request]
jobs:
  unit_tests:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Dependencies
        run: python3 -m pip install pytest docker ansible

      - name: Run Tests
        run: python3 -m pytest './tests/unit/' -s

  dependencies:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Traefik'
            role: 'traefik'
          - name: 'Postgres'
            role: 'postgres'
          - name: 'OpenLDAP'
            role: 'ldap'
          - name: 'MongoDB'
            role: 'mongo'
    name: 'App: ${{ matrix.name }} (dependency)'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [unit_tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate playbook
        run: |
          echo "---" > integration.yml
          echo "- hosts: homelab" >> integration.yml
          echo "  roles:" >> integration.yml
          echo "    - ${{ matrix.role }}" >> integration.yml

      - name: Ansible
        run: |
          for f in ./group_vars/homelab/*.yml.sample; do mv -- "$f" "${f%.yml.sample}.yml"; done
          ansible-playbook integration.yml -v

      - name: Dump logs
        if: ${{ always() }}
        run: |
          mkdir -p /tmp/docker/{logs,inspect}
          containers=$(docker ps -a | awk '{if(NR>1) print $NF}')
          for container in $containers
          do
            docker logs $container > /tmp/docker/logs/$container.log
            docker inspect $container > /tmp/docker/inspect/$container.log
          done

      - name: Store logs as artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }} (dependency) Logs
          path: /tmp/docker/

  apps:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Haste'
            role: 'haste'
          - name: 'Portainer'
            role: 'portainer'
          - name: 'phpLDAPadmin'
            role: 'phpldapadmin'
          - name: 'Adminer'
            role: 'adminer'
          - name: 'FileBrowser'
            role: 'filebrowser'
          - name: 'DevDocs'
            role: 'devdocs'
          - name: 'NextCloud'
            role: 'nextcloud'
          - name: 'Matrix'
            role: 'matrix'
    name: 'App: ${{ matrix.name }}'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [dependencies]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate playbook
        run: |
          echo "---" > integration.yml
          echo "- hosts: homelab" >> integration.yml
          echo "  roles:" >> integration.yml
          echo "    - ${{ matrix.role }}" >> integration.yml

      - name: Ansible
        run: |
          for f in ./group_vars/homelab/*.yml.sample; do mv -- "$f" "${f%.yml.sample}.yml"; done
          ansible-playbook integration.yml -v

      - name: Dump logs
        if: ${{ always() }}
        run: |
          mkdir -p /tmp/docker/{logs,inspect}
          containers=$(docker ps -a | awk '{if(NR>1) print $NF}')
          for container in $containers
          do
            docker logs $container > /tmp/docker/logs/$container.log
            docker inspect $container > /tmp/docker/inspect/$container.log
          done

      - name: Store logs as artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }} Logs
          path: /tmp/docker/
