apiVersion: v1
kind: Service
metadata:
  name: {{ include "zfsprom.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zfsprom.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9901'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9901
      protocol: TCP
      name: metrics
  selector:
    {{- include "zfsprom.selectorLabels" . | nindent 4 }}
